# -*- coding: utf-8 -*-
"""ESPRNetworkX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUtdN29QQWGvny_JFmqPQaVlDINXFhmI
"""

import networkx as nx
import matplotlib.pyplot as plt

# ----------------------------------------------------------
# 1. Create directed graph
# ----------------------------------------------------------
G = nx.DiGraph()

# ----------------------------------------------------------
# 2. Define edges and capacities
# ----------------------------------------------------------
edges = {
    ("Z1", "Z2"): 2000,
    ("Z1", "Z3"): 1600,
    ("Z10", "Z11"): 500,
    ("Z2", "Z3"): 250,
    ("Z2", "Z4"): 3000,
    ("Z2", "Z5"): 1000,
    ("Z3", "Z8"): 1000,
    ("Z3", "Z9"): 400,
    ("Z4", "Z5"): 2000,
    ("Z4", "Z6"): 2000,
    ("Z4", "Z7"): 3000,
    ("Z5", "Z7"): 2000,
    ("Z6", "Z11"): 1500,
    ("Z6", "Z7"): 2000,
    ("Z7", "Z11"): 1200,
    ("Z8", "Z10"): 1600,
    ("Z8", "Z9"): 1000,
    ("Z9", "Z10"): 500
}

# ----------------------------------------------------------
# 3. Add edges with capacities
# ----------------------------------------------------------
for (u, v), cap in edges.items():
    G.add_edge(u, v, capacity=cap)

# ----------------------------------------------------------
# 4. Generate layout (hierarchical-like using graphviz fallback)
# ----------------------------------------------------------
try:
    pos = nx.nx_agraph.graphviz_layout(G, prog="dot")
except:
    pos = nx.spring_layout(G, seed=42)

# ----------------------------------------------------------
# 5. Draw the graph
# ----------------------------------------------------------
plt.figure(figsize=(10, 8))

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=1200,
    node_color="#D0E4FF",
    font_size=10,
    arrows=True,
    arrowstyle="-|>",
)

# Edge labels (capacities)
capacities = {e: f"{data['capacity']}" for e, data in G.edges.items()}
nx.draw_networkx_edge_labels(G, pos, edge_labels=capacities, font_size=8)

# -----------------------------------------------------
# REMOVE # IN THE FOLLOWING THREE CODE LINES TO DRAW THE NETWORK FLOW GRAPH
# -----------------------------------------------------

#plt.title("Directed Graph with Capacity Upper Bounds")
#plt.tight_layout()
#plt.show()

# ----------------------------------------------------------
# 6. Compute maximum flow (with computation time) from Z1 to Z11
# ----------------------------------------------------------
import time
start_time = time.time()
flow_value, flow_dict = nx.maximum_flow(G, "Z1", "Z11")
end_time = time.time()

elapsed = end_time - start_time
print("\nMax flow from Z1 to Z11:", flow_value)
print("\nFlow distribution:")
for u, flows in flow_dict.items():
  print(u, flows)

print("\nComputation time (s):", elapsed)



